language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
before_script:
- "chmod 777 ./build-apk.sh" 
script:
- "./build-apk.sh"
notifications:
    slack: lp-iem:kDPhwslAWdRY6xk89yHqyL9i
